from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from evidence_quarantine.models import QuarantineRequest, RiskLevel, to_jsonable
from evidence_quarantine.quarantine_manager import QuarantineManager
from evidence_quarantine.time_utils import utc_now


class LabDetector:
    """Safe detector shim for lab demonstrations.

    This class does not exploit, hide, persist, or execute artifacts. It only reads
    benign alerts generated by RootkitLabSimulator and forwards them to the
    Evidence & Quarantine Manager.
    """

    def __init__(self, manager: QuarantineManager) -> None:
        self.manager = manager

    def process_alerts_file(self, alerts_file: Path) -> dict[str, Any]:
        alerts_file = alerts_file.expanduser().resolve()
        with alerts_file.open("r", encoding="utf-8") as handle:
            bundle = json.load(handle)

        results = []
        for alert in bundle.get("alerts", []):
            result = self.manager.quarantine_artifact(
                QuarantineRequest(
                    alert_id=alert.get("alert_id"),
                    artifact_path=Path(alert["artifact_path"]),
                    detection_reason=alert["detection_reason"],
                    risk_level=RiskLevel(alert.get("risk_level", RiskLevel.MEDIUM.value)),
                    detected_at=alert.get("detected_at") or utc_now(),
                    source_module="victim-lab-detector",
                    tags=[*alert.get("tags", []), "detected-by-victim-agent"],
                )
            )
            results.append(result.to_summary())

        return to_jsonable(
            {
                "detector": "victim-lab-detector",
                "alerts_file": alerts_file,
                "processed_alerts": len(results),
                "quarantine_results": results,
            }
        )

